version: 2.1

orbs:
  snyk: snyk/snyk@2.2.0

executors:
  go:
    docker:
      - image: cimg/go:1.23

jobs:
  vulnerability-scan:
    executor: go
    steps:
      - checkout
      - run:
          name: Setup Scanning
          command: |
              git config --global url."https://$GITHUB_USER:$GITHUB_TOKEN@github.com/circleci/".insteadOf "https://github.com/circleci/"
      - run:
          name: Launching Snyk Orb Scanning
          command: echo "Running snyk/scan and displaying the results"
      - snyk/scan:
          organization: "circleci-public"
          fail-on-issues: true
          severity-threshold: high
          monitor-on-build: false
          additional-arguments: "--all-projects"

workflows:
  main:
    jobs:
      - vulnerability-scan:
          context: org-global-employees
